### ISSUE TITLE
Screenshots in Readme

### ISSUE THREAD

**Issue by luzpaz** [opensourcedesign/slick#17] opened 2015-06-29 16:26 UTC
Can you please add Screenshots of how the theme looks like ? Thanks

**Comment by urbels** [comment] 2015-09-14 14:18
+1

**Comment by simonv3** [comment] 2015-09-14 17:40
That's a great idea. Be happy to accept any PRs on this if you've been playing around with Slick.

**Comment by Spodess** [comment] 2016-08-03 05:32
+1

**Comment by nhooyr** [comment] 2017-01-28 10:50
Duplicate of #6

**Comment by jancborchardt** [comment] 2017-01-31 16:34
Closing as duplicate of https://github.com/opensourcedesign/slick/issues/6

**Closed as completed by jancborchardt** 2017-01-31 16:34 UTC
